variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    environment: dev
    SecretsFilter: '$(akv)'    
    resourceGroup_ala: RG-DEV-APP
    connectionService: azure-spn
    overrideParameters: ''    
    akv: dev-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    environment: sit
    SecretsFilter: '$(akv)'    
    resourceGroup_ala: RG-SIT-APP
    connectionService: azure-spn
    overrideParameters: ''    
    akv: sit-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    environment: uat
    SecretsFilter: '$(akv)'    
    resourceGroup_ala: RG-UAT-APP
    connectionService: azure-spn
    overrideParameters: ''    
    akv: uat-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    environment: prd
    SecretsFilter: '$(akv)'    
    resourceGroup_ala: RG-PRD-APP
    connectionService: azure-spn
    overrideParameters: ''    
    akv: prd-akv-001