name: $(moduleName)-$(moduleVersion)

variables:
- template: MySQL.pipeline.variables.yaml
- template: MySQL.pipeline.environments.yaml

trigger:
  branches:
    include:
      - develop
      - staging
      - release
      - master
  paths:
    include:
      - Modules/MySQL/2.0

stages:
- stage: Build
  jobs:
  - template: MySQL.pipeline.build.yaml

- stage: Validate
  jobs:
  - template: MySQL.pipeline.validate.yaml

- stage: Deploy
  jobs:
  - template: MySQL.pipeline.deploy.yaml