variables:
  moduleName: KubernetesAKS
  moduleVersion: 2.0
  moduleTier: Modules
  moduleSolutionName: KubernetesAKS_2.0
  modulePath: $(moduleTier)/$(moduleName)/$(moduleVersion)

  artifactName: Artifacts
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  location: Australia East
  poolName: Hosted VS2017

  templateFile: '$(System.ArtifactsDirectory)/$(artifactName)/$(moduleSolutionName)/Templates/$(moduleName).mid.deploy.json'
  parametersFile: '$(System.ArtifactsDirectory)/$(artifactName)/$(moduleSolutionName)/Templates/$(moduleName).mid.parameters.$(environment).json'