name: $(applicationName)-$(applicationVersion)

variables:
- template: pipeline.variables.yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - Environments/HubNetworkServices/*

stages:
- stage: Build
  jobs:
  - template: ../../Modules/RouteTables/2.1/Pipeline/pipeline.jobs.build.yaml
    parameters:
      poolName: $(poolName)
      moduleUnitTestParametersLocation: '$(applicationParametersLocation)/RouteTables'
  - template: ../../Modules/NetworkSecurityGroups/2.1/Pipeline/pipeline.jobs.build.yaml
    parameters:
      poolName: $(poolName)
      moduleUnitTestParametersLocation: '$(applicationParametersLocation)/NetworkSecurityGroups'
  - template: ../../Modules/VirtualNetwork/2.1/Pipeline/pipeline.jobs.build.yaml
    parameters:
      poolName: $(poolName)
      moduleUnitTestParametersLocation: '$(applicationParametersLocation)/VirtualNetwork'
  - template: ../../Modules/PublicIpPrefixes/2.1/Pipeline/pipeline.jobs.build.yaml
    parameters:
      poolName: $(poolName)
      moduleUnitTestParametersLocation: '$(applicationParametersLocation)/PIPPrefix'
  - template: ../../Modules/VirtualNetworkGateway/2.1/Pipeline/pipeline.jobs.build.yaml
    parameters:
      poolName: $(poolName)
      moduleUnitTestParametersLocation: '$(applicationParametersLocation)/VirtualNetworkGateway'
  - template: ../../Modules/VirtualNetworkGatewayConnection/2.1/Pipeline/pipeline.jobs.build.yaml
    parameters:
      poolName: $(poolName)
      moduleUnitTestParametersLocation: '$(applicationParametersLocation)/VirtualNetworkGatewayConnection'

- stage: Validate
  jobs:
  - template: ../../Modules/RouteTables/2.1/Pipeline/pipeline.jobs.validate.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/RouteTables/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/NetworkSecurityGroups/2.1/Pipeline/pipeline.jobs.validate.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/NetworkSecurityGroups/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/VirtualNetwork/2.1/Pipeline/pipeline.jobs.validate.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/VirtualNetwork/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/PublicIpPrefixes/2.1/Pipeline/pipeline.jobs.validate.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/PIPPrefix/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/VirtualNetworkGateway/2.1/Pipeline/pipeline.jobs.validate.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/VirtualNetworkGateway/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/VirtualNetworkGatewayConnection/2.1/Pipeline/pipeline.jobs.validate.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/VirtualNetworkGatewayConnection/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)

- stage: Deploy
  jobs:
  - template: ../../Modules/RouteTables/2.1/Pipeline/pipeline.jobs.deploy.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/RouteTables/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/NetworkSecurityGroups/2.1/Pipeline/pipeline.jobs.deploy.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/NetworkSecurityGroups/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/VirtualNetwork/2.1/Pipeline/pipeline.jobs.deploy.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/VirtualNetwork/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/PublicIpPrefixes/2.1/Pipeline/pipeline.jobs.deploy.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/PIPPrefix/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/VirtualNetworkGateway/2.1/Pipeline/pipeline.jobs.deploy.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/VirtualNetworkGateway/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)
  - template: ../../Modules/VirtualNetworkGatewayConnection/2.1/Pipeline/pipeline.jobs.deploy.yaml
    parameters:
      poolName: $(poolName)
      parametersFile: 'Environments/$(applicationName)/Parameters/VirtualNetworkGatewayConnection/parameters.json'
      overrideParameters: ''
      serviceConnection: $(serviceConnection)
      resourceGroupName: $(resourceGroupName)
      location: $(location)