name: $(moduleName)-$(moduleVersion)

variables:
- template: FunctionApps.pipeline.variables.yaml
- template: FunctionApps.pipeline.environments.yaml

trigger:
  branches:
    include:
      - develop
      - staging
      - release
      - master
  paths:
    include:
      - Modules/FunctionApps/2.0

stages:
- stage: Build
  jobs:
  - template: FunctionApps.pipeline.build.yaml

- stage: Validate
  jobs:
  - template: FunctionApps.pipeline.validate.yaml

- stage: Deploy
  jobs:
  - template: FunctionApps.pipeline.deploy.yaml