name: $(moduleName)-$(moduleVersion)

variables:
- template: Cosmosdb.pipeline.variables.yaml
- template: Cosmosdb.pipeline.environments.yaml

trigger:
  branches:
    include:
      - develop
      - staging
      - release
      - master
  paths:
    include:
      - Modules/Cosmosdb/2.0

stages:
- stage: Build
  jobs:
  - template: Cosmosdb.pipeline.build.yaml

- stage: Validate
  jobs:
  - template: Cosmosdb.pipeline.validate.yaml

- stage: Deploy
  jobs:
  - template: Cosmosdb.pipeline.deploy.yaml