parameters:
  moduleName: BatchAccounts
  moduleVersion: $(moduleVersion)
  moduleTier: $(moduleTier)
  artifactName: $(artifactName)
  connectionService: $(connectionService)
  resourceGroup: $(resourceGroup)
  templateFile: $(templatefile)
  parametersFile: $(parametersfile)

jobs:
  - job: 'ValidateModule_${{ parameters.moduleName }}'
    displayName: 'Validate Module ${{ parameters.moduleName }}'
    pool:
      name: $(poolName)
    workspace:
      clean: all
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '${{ parameters.artifactName }}'
        downloadPath: $(System.ArtifactsDirectory)

    - task: AzureResourceGroupDeployment@2
      displayName: 'Validate ${{ parameters.moduleName }}'
      inputs:
        azureSubscription: '${{ parameters.connectionService }}'
        resourceGroupName: '${{ parameters.resourceGroup }}'
        location: '${{ parameters.location }}'
        csmFile: '${{ parameters.templateFile }}'
        csmParametersFile: '${{ parameters.parametersFile }}'
        deploymentMode: Validation