variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    environment: dev
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'      
    resourceGroup: RG-DEV-SHD
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--myscdevdiag001)" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--myscdevmon001)"'    
    akv: dev-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    environment: sit
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'      
    resourceGroup: RG-SIT-SHD
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--myscdevdiag001)" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--myscdevmon001)"'    
    akv: sit-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    environment: uat
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'      
    resourceGroup: RG-UAT-SHD
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--myscdevdiag001)" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--myscdevmon001)"'    
    akv: uat-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    environment: prd
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>,StorageAccount--ResourceId--<ResourceNameHere>'      
    resourceGroup: RG-PRD-SHD
    connectionService: azure-spn
    overrideParameters: '-diagnosticStorageAccountId "$(StorageAccount--ResourceId--myscdevdiag001)" -logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--myscdevmon001)"'    
    akv: prd-akv-001