variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    environment: dev
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>'    
    resourceGroup_kub: RG-DEV-KUB
    connectionService: azure-spn
    overrideParameters: '-logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: dev-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    environment: sit
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>'    
    resourceGroup_kub: RG-SIT-KUB
    connectionService: azure-spn
    overrideParameters: '-logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: sit-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release') }}:
    environment: uat
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>'    
    resourceGroup_kub: RG-UAT-KUB
    connectionService: azure-spn
    overrideParameters: '-logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: uat-akv-001

  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    environment: prd
    secretsFilter: 'LogAnalytics--ResourceId--<ResourceNameHere>'    
    resourceGroup_kub: RG-PRD-KUB
    connectionService: azure-spn
    overrideParameters: '-logAnalyticsWorkspaceId "$(LogAnalytics--ResourceId--<ResourceNameHere>)"'    
    akv: prd-akv-001