parameters:
  moduleName: PostgreSQL
  moduleVersion: 2.0
  moduleTier: Modules
  moduleSolutionName: PostgreSQL_2.0
  artifactName: $(artifactName)
  connectionService: $(connectionService)
  resourceGroup: $(resourceGroup)
  environment: $(environment)
  location: $(location)
  templateFile: $(templatefile)
  parametersFile: $(parametersfile)

jobs:
  - job: 'ValidateModule_${{ parameters.moduleName }}'
    displayName: 'Validate Module ${{ parameters.moduleName }}'
    pool:
      name: $(poolName)
    workspace:
      clean: all
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '${{ parameters.artifactName }}'
        downloadPath: $(System.ArtifactsDirectory)
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          Write-Host $(System.ArtifactsDirectory)
          Write-Host $(templatefile)
          Write-Host $(parametersfile)
          Write-Host $(resourceGroup)
          Write-Host $(env)
    - task: AzureResourceGroupDeployment@2
      enabled: true
      displayName: 'Validate ${{ parameters.moduleName }}'
      inputs:
        azureSubscription: '${{ parameters.connectionService }}'
        resourceGroupName: '${{ parameters.resourceGroup }}'
        location: '${{ parameters.location }}'
        csmFile: '${{ parameters.templateFile }}'
        csmParametersFile: '${{ parameters.parametersFile }}'
        deploymentMode: Validation