name: $(moduleName)-$(moduleVersion)

variables:
- template: PostgreSQL.pipeline.variables.yaml
- template: PostgreSQL.pipeline.environments.yaml

trigger:
  branches:
    include:
      - develop
      - staging
      - release
      - master
  paths:
    include:
      - Modules/PostgreSQL/2.0/*

stages:
- stage: Build
  jobs:
  - template: PostgreSQL.pipeline.build.yaml

- stage: Validate
  jobs:
  - template: PostgreSQL.pipeline.validate.yaml

- stage: Deploy
  jobs:
  - template: PostgreSQL.pipeline.deploy.yaml
